Update detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -5,10 +5,13 @@ echo "Working directory: $(pwd)"
 
 echo "Checking for Aptfile in: $1" 
 
+#!/usr/bin/env bash
+# bin/detect <build-dir>
+
 if [[ -f "$1/Aptfile" ]]; then
   echo "Apt"
   exit 0
 else
-  echo "'Aptfile' not found. Creating a default one..."
-  echo -e "unixodbc\nunixodbc-dev" > "$1/new_directory/Aptfile"
+  echo "Could not find an 'Aptfile'! Please ensure it exists and is checked into Git." >&2
+  exit 1
 fi
